- name: Installed mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: installed mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: Installed
